/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iudesign;

import Clases.ComprobarConexionInternet;
import Clases.SimpleFactory;
import java.awt.Color;
import java.io.IOException;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author m98am
 */
public class menú extends javax.swing.JFrame {

    /**
     * Creates new form menú
     */
    //Manejo de variables
    private static String fullName, materia;

    public menú(String fullName, String materia) {
        initComponents();
        setLocationRelativeTo(null);
        PanelInfo.setVisible(false);

        //Dandole valor a las variables globales
        this.fullName = fullName;
        this.materia = materia;

        //Haciendo que los labels tengan los valores que deben
        menú.JlabelFullName.setText(fullName);
        menú.jLabelmateria.setText(materia);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        JlabelFullName = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        brnCerrarSesion = new javax.swing.JButton();
        jLabelmateria = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnIngresarNotas = new javax.swing.JButton();
        btnModificarNotas = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnMatricularAlumno = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        BtnCerrar = new javax.swing.JLabel();
        btnMinimizar = new javax.swing.JLabel();
        PanelInfo = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 51));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 0, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240), 5));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Complejo Educativo Confederación Suiza");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(614, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(503, 503, 503))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 690, 1360, 50));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240), 2));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_User_96px_3.png"))); // NOI18N

        JlabelFullName.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        JlabelFullName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JlabelFullName.setText("          Usuario");

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        brnCerrarSesion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        brnCerrarSesion.setText("Cerrar sesión");
        brnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brnCerrarSesionActionPerformed(evt);
            }
        });

        jLabelmateria.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelmateria.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelmateria.setText("Nombre del curso");

        jLabel14.setText("Desde aquí puedes añadir estudiantes a la nómina.");

        jLabel15.setText("Ingresar y modificar notas. ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jLabel10))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(brnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel14))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel15))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelmateria, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                                .addComponent(JlabelFullName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabelmateria)
                .addGap(69, 69, 69)
                .addComponent(jLabel10)
                .addGap(31, 31, 31)
                .addComponent(JlabelFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(brnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 330, 630));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("Modificar notas");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 370, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("Ingresar notas");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 370, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Laptop_96px.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 280, -1, -1));

        btnIngresarNotas.setBackground(new java.awt.Color(69, 113, 143));
        btnIngresarNotas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/books gif.gif"))); // NOI18N
        btnIngresarNotas.setBorder(null);
        btnIngresarNotas.setBorderPainted(false);
        btnIngresarNotas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIngresarNotas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnIngresarNotasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnIngresarNotasMouseExited(evt);
            }
        });
        getContentPane().add(btnIngresarNotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 250, 240, 150));

        btnModificarNotas.setBackground(new java.awt.Color(3, 57, 57));
        btnModificarNotas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/e8e35fafa9e5282b5de8478e7febaf0d2dd79123_hq.gif"))); // NOI18N
        btnModificarNotas.setBorder(null);
        btnModificarNotas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModificarNotas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnModificarNotasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnModificarNotasMouseExited(evt);
            }
        });
        getContentPane().add(btnModificarNotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 250, 240, 150));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("Matricular alumno");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Student_Male_96px.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, -1, -1));

        btnMatricularAlumno.setBackground(new java.awt.Color(151, 20, 64));
        btnMatricularAlumno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/scale.gif"))); // NOI18N
        btnMatricularAlumno.setBorder(null);
        btnMatricularAlumno.setBorderPainted(false);
        btnMatricularAlumno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMatricularAlumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMatricularAlumnoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMatricularAlumnoMouseExited(evt);
            }
        });
        btnMatricularAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMatricularAlumnoActionPerformed(evt);
            }
        });
        getContentPane().add(btnMatricularAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, 240, 150));

        jPanel6.setBackground(new java.awt.Color(0, 0, 51));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240), 2));

        jLabel9.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(240, 240, 240));
        jLabel9.setText("ADMINISTRACIÓN ACADÉMICA");

        BtnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Close_Window_32px.png"))); // NOI18N
        BtnCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnCerrarMouseClicked(evt);
            }
        });

        btnMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Horizontal_Line_32px.png"))); // NOI18N
        btnMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(617, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(400, 400, 400)
                .addComponent(btnMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addContainerGap())
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnCerrar)
                    .addComponent(btnMinimizar))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1340, 50));

        PanelInfo.setBackground(new java.awt.Color(0, 0, 0));
        PanelInfo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(240, 240, 240), 1, true));
        PanelInfo.setForeground(new java.awt.Color(0, 0, 51));
        PanelInfo.setOpaque(false);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(240, 240, 240));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Attention_32px.png"))); // NOI18N

        javax.swing.GroupLayout PanelInfoLayout = new javax.swing.GroupLayout(PanelInfo);
        PanelInfo.setLayout(PanelInfoLayout);
        PanelInfoLayout.setHorizontalGroup(
            PanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelInfoLayout.createSequentialGroup()
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );
        PanelInfoLayout.setVerticalGroup(
            PanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelInfoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(PanelInfoLayout.createSequentialGroup()
                .addComponent(jLabel16)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(PanelInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 510, 620, 50));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/IMG_0849[1152].JPG"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 1000, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMatricularAlumnoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMatricularAlumnoMouseEntered
        PanelInfo.setVisible(true);
        jLabel13.setText("Matricula a un estudiante como miembro del Complejo Educativo Confederacion Suiza");

// TODO add your handling code here:
    }//GEN-LAST:event_btnMatricularAlumnoMouseEntered

    private void btnMatricularAlumnoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMatricularAlumnoMouseExited
        PanelInfo.setVisible(false);
        jLabel13.setText("");

        // TODO add your handling code here:
    }//GEN-LAST:event_btnMatricularAlumnoMouseExited

    private void btnIngresarNotasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresarNotasMouseEntered
        PanelInfo.setVisible(true);
        jLabel13.setText("                         Ingresa las calificaciones del periodo correspondiente");
    }//GEN-LAST:event_btnIngresarNotasMouseEntered

    private void btnIngresarNotasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresarNotasMouseExited
        PanelInfo.setVisible(false);
        jLabel13.setText("");
    }//GEN-LAST:event_btnIngresarNotasMouseExited

    private void btnModificarNotasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarNotasMouseEntered
        PanelInfo.setVisible(true);
        jLabel13.setText("                                       Modifica las notas de tus alumnos");
    }//GEN-LAST:event_btnModificarNotasMouseEntered

    private void btnModificarNotasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarNotasMouseExited
        PanelInfo.setVisible(false);
        jLabel13.setText("");
    }//GEN-LAST:event_btnModificarNotasMouseExited

    private void btnMatricularAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatricularAlumnoActionPerformed

        //Creando una nueva instancia, un metodo de ella nos permite verificar la conexion a internet
        ComprobarConexionInternet i = new ComprobarConexionInternet();
        if (i.comprobarConexion()) {
            this.setVisible(false);
            //Abrir nueva ventana, sin cerrar el menú
            SimpleFactory simpleFactory = new SimpleFactory();
            simpleFactory.constructorObjetosVariables(2, fullName, materia);
            simpleFactory = null;
            //new matricula(fullName, materia).setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnMatricularAlumnoActionPerformed

    private void brnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brnCerrarSesionActionPerformed
        SimpleFactory simpleFactory = new SimpleFactory();
        simpleFactory.constructorObjetos(2); //Login
        simpleFactory = null;
    }//GEN-LAST:event_brnCerrarSesionActionPerformed

    private void BtnCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCerrarMouseClicked
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_BtnCerrarMouseClicked

    private void btnMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizarMouseClicked
        this.setExtendedState(1);
    }//GEN-LAST:event_btnMinimizarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menú.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menú.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menú.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menú.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menú(fullName, materia).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BtnCerrar;
    public static javax.swing.JLabel JlabelFullName;
    private javax.swing.JPanel PanelInfo;
    private javax.swing.JButton brnCerrarSesion;
    private javax.swing.JButton btnIngresarNotas;
    private javax.swing.JButton btnMatricularAlumno;
    private javax.swing.JLabel btnMinimizar;
    private javax.swing.JButton btnModificarNotas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JLabel jLabelmateria;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
